services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private_network

  postgres_ui:
    image: dpage/pgadmin4:latest
    container_name: postgres_ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - private_network
    depends_on:
      - postgres_db

  webapi:
    image: financas21_webapi
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    environment:
      - RunMigration=true
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Host=postgres_db;Database=main;Username=admin;Password=admin
    networks:
      - private_network
    ports:
      - 8080:8080
    depends_on:
      - postgres_db

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  private_network:
    driver: bridge
